# Manully keep alive on on Jun 23, 2023
#https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: Create and publish a Docker image to Docker Hub

on:
  schedule:
    - cron: '54 4 4 * *'
  push:
    branches: "main"


env:
  IMAGE_NAME: yangwu91/ubuntu


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Get the date
        id: date
        run: |
          echo "DATE=$(date +%Y.%m)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.date.outputs.DATE }},${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
